class snehasish
     {
     public private void main()
          {
            int a,b,c,i;
            for(i=0;i<=n;i++)
            {
            for(a=0;a<=i;a++)
            {
              a=c;
              c=a;
              c+1=a;
              }
              for(b=0;b<=a;b++)
              {
              b=c;
              c=b;
              c+1=b;}
              }
              }
              }
              
